#!/usr/bin/env php
<?php

/**
 * JBZoo Toolbox - Cli
 *
 * This file is part of the JBZoo Toolbox project.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @package    Cli
 * @license    MIT
 * @copyright  Copyright (C) JBZoo.com, All rights reserved.
 * @link       https://github.com/JBZoo/Cli
 */

declare(strict_types=1);

namespace DemoApp;

use JBZoo\Cli\CliApplication;

require_once dirname(__DIR__) . '/vendor/autoload.php';

$application = new CliApplication('Example CLI Application', 'v1.0.0');
$application->registerCommandsByPath(__DIR__ . '/Commands', __NAMESPACE__);
// $application->setDefaultCommand('simple');

$application->run();
