#
# JBZoo Toolbox - Cli
#
# This file is part of the JBZoo Toolbox project.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#
# @package    Cli
# @license    MIT
# @copyright  Copyright (C) JBZoo.com, All rights reserved.
# @link       https://github.com/JBZoo/Cli
#

name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - 'master'
  schedule:
    - cron: '45 */8 * * *'

env:
  COLUMNS: 120
  TERM_PROGRAM: Hyper

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    env:
      JBZOO_COMPOSER_UPDATE_FLAGS: ${{ matrix.composer_flags }}
    strategy:
      matrix:
        php-version: [ 7.2, 7.3, 7.4 ]
        composer_flags: [ "--prefer-lowest", "" ]
        include:
          - php-version: "8.0"
          - php-version: "8.1"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer

      - name: Build the Project
        run: make update --no-print-directory

      - name: 🧪 PHPUnit Tests
        run: make test --no-print-directory

      - name: Uploading coverage to coveralls
        env:
            COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make report-coveralls --no-print-directory

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PHPUnit - ${{ matrix.php-version }} ${{ matrix.composer_flags }}
          path: build/


  linters:
    name: Linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.2, 7.3, 7.4, 8.0 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer

      - name: Build the Project
        run: make update --no-print-directory

      - name: 👍 Code Quality
        run: make codestyle --no-print-directory

      - name: 👍 Code Quality (Demo App)
        run: make codestyle PATH_SRC=./demo --no-print-directory

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Linters - ${{ matrix.php-version }}
          path: build/


  report:
    name: Reports
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 7.2, 7.3, 7.4, 8.0 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer

      - name: Build the Project
        run: make update --no-print-directory

      - name: 📝 Build Reports
        run: make report-all --no-print-directory

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Reports - ${{ matrix.php-version }}
          path: build/
